### ISSUE TITLE
Uvoz zemljevida

### ISSUE THREAD

**Issue by JernejcicZan** [JernejcicZan/APPR-2018-19#1]
Pozdravljeni, pri projektu potrebujem  uvoz zemljevida. To sem naredil tako kot eden od sošolcev, ampak imam težave saj mi izpiše:
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
Hvala za pomoč.

**Comment by jaanos** [comment]
V `uvozi.zemljevid.r` popravi

https://github.com/JernejcicZan/APPR-2018-19/blob/e6ba1961b9f6080cb8f62115f47a1d4f00625a77/lib/uvozi.zemljevid.r#L53

v

```R
    zemljevid <- readOGR(shp, ime.zemljevida)
```

Potem bi moralo delovati.

**Comment by JernejcicZan** [comment]
Hvala lepa!
